In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("students.csv")

print("Student Dataset:")
display(df)

Student Dataset:

,Student_ID,Name,Department,Python,SQL,HTML,CSS,JavaScript,Attendance
0,101,Anjali,AIML,85,78,90,88,82,92
1,102,Rahul,CSE,72,80,75,70,78,85
2,103,Sneha,AIML,95,92,88,94,96,98
3,104,Arjun,CSE,60,65,58,62,70,75
4,105,Priya,AIML,88,85,91,89,90,94
5,106,Kiran,ECE,78,70,83,75,80,88
6,107,Divya,CSE,91,88,94,90,93,96
7,108,Rohit,AIML,67,73,70,68,65,72
8,109,Meena,ECE,82,79,85,81,88,89
9,110,Vijay,CSE,74,68,77,72,75,81
10,111,Asha,AIML,93,90,86,92,89,97
11,112,Varun,ECE,56,61,64,59,63,68
12,113,Neha,CSE,86,83,92,87,91,93
13,114,Suresh,AIML,69,72,67,65,71,78
14,115,Kavya,ECE,90,94,89,91,85,95
15,116,Manoj,CSE,77,76,80,78,79,84
16,117,Pooja,AIML,84,81,95,86,92,91
17,118,Aditya,ECE,62,58,71,60,66,70
18,119,Swathi,CSE,96,89,93,95,94,99
19,120,Ravi,AIML,80,87,84,82,83,87

In [ ]:
print("First 5 students:")
display(df.head())

First 5 students:

,Student_ID,Name,Department,Python,SQL,HTML,CSS,JavaScript,Attendance
0,101,Anjali,AIML,85,78,90,88,82,92
1,102,Rahul,CSE,72,80,75,70,78,85
2,103,Sneha,AIML,95,92,88,94,96,98
3,104,Arjun,CSE,60,65,58,62,70,75
4,105,Priya,AIML,88,85,91,89,90,94

In [ ]:
print("Dataset shape:")
print(df.shape)

Dataset shape:
(20, 9)

In [ ]:
print("Column names:")
print(df.columns.tolist())

Column names:
['Student_ID', 'Name', 'Department', 'Python', 'SQL', 'HTML', 'CSS', 'JavaScript', 'Attendance']

In [ ]:
print("Dataset information:")
df.info()

Dataset information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  20 non-null     int64
 1   Name        20 non-null     object
 2   Department  20 non-null     object
 3   Python      20 non-null     int64
 4   SQL         20 non-null     int64
 5   HTML        20 non-null     int64
 6   CSS         20 non-null     int64
 7   JavaScript  20 non-null     int64
 8   Attendance  20 non-null     int64
dtypes: int64(7), object(2)
memory usage: 1.5+ KB

In [ ]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Student_ID    0
Name          0
Department    0
Python        0
SQL           0
HTML          0
CSS           0
JavaScript    0
Attendance    0
dtype: int64

In [ ]:
subjects = ["Python", "SQL", "HTML", "CSS", "JavaScript"]

df["Total"] = df[subjects].sum(axis=1)

df["Average"] = df[subjects].mean(axis=1).round(2)

display(df[["Student_ID", "Name", "Total", "Average"]])

    Student_ID    Name  Total  Average
0          101  Anjali    423     84.6
1          102   Rahul    375     75.0
2          103   Sneha    465     93.0
3          104   Arjun    315     63.0
4          105   Priya    443     88.6
5          106   Kiran    386     77.2
6          107   Divya    456     91.2
7          108   Rohit    343     68.6
8          109   Meena    415     83.0
9          110   Vijay    366     73.2
10         111    Asha    450     90.0
11         112   Varun    303     60.6
12         113    Neha    439     87.8
13         114  Suresh    344     68.8
14         115   Kavya    449     89.8
15         116   Manoj    390     78.0
16         117   Pooja    438     87.6
17         118  Aditya    317     63.4
18         119  Swathi    467     93.4
19         120    Ravi    416     83.2

In [ ]:
def calculate_grade(average):
    if average >= 90:
        return "A"
    elif average >= 80:
        return "B"
    elif average >= 70:
        return "C"
    elif average >= 60:
        return "D"
    else:
        return "F"

df["Grade"] = df["Average"].apply(calculate_grade)

display(df[["Student_ID", "Name", "Average", "Grade"]])

    Student_ID    Name  Average Grade
0          101  Anjali     84.6     B
1          102   Rahul     75.0     C
2          103   Sneha     93.0     A
3          104   Arjun     63.0     D
4          105   Priya     88.6     B
5          106   Kiran     77.2     C
6          107   Divya     91.2     A
7          108   Rohit     68.6     D
8          109   Meena     83.0     B
9          110   Vijay     73.2     C
10         111    Asha     90.0     A
11         112   Varun     60.6     D
12         113    Neha     87.8     B
13         114  Suresh     68.8     D
14         115   Kavya     89.8     B
15         116   Manoj     78.0     C
16         117   Pooja     87.6     B
17         118  Aditya     63.4     D
18         119  Swathi     93.4     A
19         120    Ravi     83.2     B

In [ ]:
df["Result"] = np.where(
    (df[subjects] >= 40).all(axis=1),
    "Pass",
    "Fail"
)

display(df[["Student_ID", "Name", "Average", "Grade", "Result"]])

    Student_ID    Name  Average Grade Result
0          101  Anjali     84.6     B   Pass
1          102   Rahul     75.0     C   Pass
2          103   Sneha     93.0     A   Pass
3          104   Arjun     63.0     D   Pass
4          105   Priya     88.6     B   Pass
5          106   Kiran     77.2     C   Pass
6          107   Divya     91.2     A   Pass
7          108   Rohit     68.6     D   Pass
8          109   Meena     83.0     B   Pass
9          110   Vijay     73.2     C   Pass
10         111    Asha     90.0     A   Pass
11         112   Varun     60.6     D   Pass
12         113    Neha     87.8     B   Pass
13         114  Suresh     68.8     D   Pass
14         115   Kavya     89.8     B   Pass
15         116   Manoj     78.0     C   Pass
16         117   Pooja     87.6     B   Pass
17         118  Aditya     63.4     D   Pass
18         119  Swathi     93.4     A   Pass
19         120    Ravi     83.2     B   Pass

In [ ]:
class_average = df["Average"].mean()

print("Class Average:", round(class_average, 2))

Class Average: 80.0

In [ ]:
topper = df.loc[df["Average"].idxmax()]

print("Top-Performing Student")
print("Name:", topper["Name"])
print("Average:", topper["Average"])
print("Grade:", topper["Grade"])

Top-Performing Student
Name: Swathi
Average: 93.4
Grade: A

In [ ]:
lowest_student = df.loc[df["Average"].idxmin()]

print("Lowest-Performing Student")
print("Name:", lowest_student["Name"])
print("Average:", lowest_student["Average"])
print("Grade:", lowest_student["Grade"])

Lowest-Performing Student
Name: Varun
Average: 60.6
Grade: D

In [ ]:
subject_averages = df[subjects].mean().round(2)

print("Average Marks by Subject:")
print(subject_averages)

print("\nHighest-Performing Subject:",
      subject_averages.idxmax())

print("Lowest-Performing Subject:",
      subject_averages.idxmin())

Average Marks by Subject:
Python        79.25
SQL           78.45
HTML          81.60
CSS           79.20
JavaScript    81.50
dtype: float64

Highest-Performing Subject: HTML
Lowest-Performing Subject: SQL

In [ ]:
result_counts = df["Result"].value_counts()

print("Pass/Fail Summary:")
print(result_counts)

Pass/Fail Summary:
Result
Pass    20
Name: count, dtype: int64

In [ ]:
print("========== STUDENT PERFORMANCE REPORT ==========")

display(df)

print("\n========== CLASS SUMMARY ==========")
print("Total Students:", len(df))
print("Class Average:", round(df["Average"].mean(), 2))
print("Students Passed:", (df["Result"] == "Pass").sum())
print("Students Failed:", (df["Result"] == "Fail").sum())

print("\n========== TOP PERFORMER ==========")
print(df.loc[df["Average"].idxmax(), ["Name", "Average", "Grade"]])

print("\n========== SUBJECT-WISE AVERAGES ==========")
print(df[subjects].mean().round(2))

========== STUDENT PERFORMANCE REPORT ==========

,Student_ID,Name,Department,Python,SQL,HTML,CSS,JavaScript,Attendance,Total,Average,Grade,Result
0,101,Anjali,AIML,85,78,90,88,82,92,423,84.6,B,Pass
1,102,Rahul,CSE,72,80,75,70,78,85,375,75.0,C,Pass
2,103,Sneha,AIML,95,92,88,94,96,98,465,93.0,A,Pass
3,104,Arjun,CSE,60,65,58,62,70,75,315,63.0,D,Pass
4,105,Priya,AIML,88,85,91,89,90,94,443,88.6,B,Pass
5,106,Kiran,ECE,78,70,83,75,80,88,386,77.2,C,Pass
6,107,Divya,CSE,91,88,94,90,93,96,456,91.2,A,Pass
7,108,Rohit,AIML,67,73,70,68,65,72,343,68.6,D,Pass
8,109,Meena,ECE,82,79,85,81,88,89,415,83.0,B,Pass
9,110,Vijay,CSE,74,68,77,72,75,81,366,73.2,C,Pass
10,111,Asha,AIML,93,90,86,92,89,97,450,90.0,A,Pass
11,112,Varun,ECE,56,61,64,59,63,68,303,60.6,D,Pass
12,113,Neha,CSE,86,83,92,87,91,93,439,87.8,B,Pass
13,114,Suresh,AIML,69,72,67,65,71,78,344,68.8,D,Pass
14,115,Kavya,ECE,90,94,89,91,85,95,449,89.8,B,Pass
15,116,Manoj,CSE,77,76,80,78,79,84,390,78.0,C,Pass
16,117,Pooja,AIML,84,81,95,86,92,91,438,87.6,B,Pass
17,118,Aditya,ECE,62,58,71,60,66,70,317,63.4,D,Pass
18,119,Swathi,CSE,96,89,93,95,94,99,467,93.4,A,Pass
19,120,Ravi,AIML,80,87,84,82,83,87,416,83.2,B,Pass

========== CLASS SUMMARY ==========
Total Students: 20
Class Average: 80.0
Students Passed: 20
Students Failed: 0

========== TOP PERFORMER ==========
Name       Swathi
Average      93.4
Grade           A
Name: 18, dtype: object

========== SUBJECT-WISE AVERAGES ==========
Python        79.25
SQL           78.45
HTML          81.60
CSS           79.20
JavaScript    81.50
dtype: float64

In [ ]:
def calculate_total(marks):
    total = np.sum(marks)
    return total


def calculate_average(marks):
    average = np.mean(marks)
    return round(average, 2)


def calculate_grade(average):
    if average >= 90:
        return "A"
    elif average >= 80:
        return "B"
    elif average >= 70:
        return "C"
    elif average >= 60:
        return "D"
    else:
        return "F"


print("Functions created successfully!")

Functions created successfully!

In [ ]:
totals = []
averages = []
grades = []

for index, row in df.iterrows():
    marks = row[subjects].to_numpy()

    total = calculate_total(marks)
    average = calculate_average(marks)
    grade = calculate_grade(average)

    totals.append(total)
    averages.append(average)
    grades.append(grade)

df["Total"] = totals
df["Average"] = averages
df["Grade"] = grades

print("Student records processed successfully!")
display(df[["Name", "Total", "Average", "Grade"]])

Student records processed successfully!

      Name  Total  Average Grade
0   Anjali    423     84.6     B
1    Rahul    375     75.0     C
2    Sneha    465     93.0     A
3    Arjun    315     63.0     D
4    Priya    443     88.6     B
5    Kiran    386     77.2     C
6    Divya    456     91.2     A
7    Rohit    343     68.6     D
8    Meena    415     83.0     B
9    Vijay    366     73.2     C
10    Asha    450     90.0     A
11   Varun    303     60.6     D
12    Neha    439     87.8     B
13  Suresh    344     68.8     D
14   Kavya    449     89.8     B
15   Manoj    390     78.0     C
16   Pooja    438     87.6     B
17  Aditya    317     63.4     D
18  Swathi    467     93.4     A
19    Ravi    416     83.2     B

In [ ]:
def check_attendance(attendance):
    if attendance >= 75:
        return "Satisfactory"
    else:
        return "Low Attendance"


df["Attendance_Status"] = df["Attendance"].apply(check_attendance)

print("Attendance Analysis:")
display(
    df[["Student_ID", "Name", "Attendance", "Attendance_Status"]]
)

Attendance Analysis:

    Student_ID    Name  Attendance Attendance_Status
0          101  Anjali          92      Satisfactory
1          102   Rahul          85      Satisfactory
2          103   Sneha          98      Satisfactory
3          104   Arjun          75      Satisfactory
4          105   Priya          94      Satisfactory
5          106   Kiran          88      Satisfactory
6          107   Divya          96      Satisfactory
7          108   Rohit          72    Low Attendance
8          109   Meena          89      Satisfactory
9          110   Vijay          81      Satisfactory
10         111    Asha          97      Satisfactory
11         112   Varun          68    Low Attendance
12         113    Neha          93      Satisfactory
13         114  Suresh          78      Satisfactory
14         115   Kavya          95      Satisfactory
15         116   Manoj          84      Satisfactory
16         117   Pooja          91      Satisfactory
17         118  Aditya          70    Low Attendance
18         119  Swathi          99      Satisfactory
19         120    Ravi          87      Satisfactory